spring.application.name=FirstSpringBoot
server.port=8091

# Database connection properties
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/firstspringboot-test
spring.datasource.username=root
spring.datasource.password=root

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update

# Disable Open-in-View to avoid potential lazy loading issues
spring.jpa.open-in-view=false

#Logging
# Set root logging level
logging.level.root=INFO
#Only adds in log file with warning occurs
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN
logging.level.org.springframework.boot.autoconfigure=WARN
# Log file path and name
logging.file.name=logs/app.log
# Optional: Log format
logging.pattern.file=[%d{yyyy-MM-dd HH:mm:ss}] %-5level %logger{36} - %msg%n